MESSAGES_MERGE_TIME_LIMIT = 120
#DEFAULT_MUL_EN_TRANSLATION_MODEL = "Helsinki-NLP/opus-mt-mul-en"
#DEFAULT_MUL_EN_TRANSLATION_MODEL = "facebook/m2m100_418M"
DEFAULT_MUL_EN_TRANSLATION_MODEL = "facebook/m2m100_1.2B"
DEFAULT_EN_MUL_TRANSLATION_MODEL = "Helsinki-NLP/opus-mt-en-mul"